<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-14T14:48:11 IST" name="Suite" finished-at="2023-09-14T14:48:12 IST" duration-ms="137">
    <groups>
    </groups>
    <test started-at="2023-09-14T14:48:11 IST" name="Test" finished-at="2023-09-14T14:48:12 IST" duration-ms="137">
      <class name="mavenpack.Testclass">
        <test-method signature="class1()[pri:0, instance:mavenpack.Testclass@82de64a]" started-at="2023-09-14T14:48:11 IST" name="class1" finished-at="2023-09-14T14:48:11 IST" duration-ms="19" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- class1 -->
        <test-method signature="class2()[pri:0, instance:mavenpack.Testclass@82de64a]" started-at="2023-09-14T14:48:11 IST" name="class2" finished-at="2023-09-14T14:48:11 IST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- class2 -->
      </class> <!-- mavenpack.Testclass -->
      <class name="mavenpack.Assertclass">
        <test-method signature="in()[pri:0, instance:mavenpack.Assertclass@59505b48]" started-at="2023-09-14T14:48:11 IST" name="in" finished-at="2023-09-14T14:48:11 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- in -->
        <test-method signature="pak()[pri:0, instance:mavenpack.Assertclass@59505b48]" started-at="2023-09-14T14:48:11 IST" name="pak" finished-at="2023-09-14T14:48:11 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pak -->
        <test-method signature="sl()[pri:0, instance:mavenpack.Assertclass@59505b48]" started-at="2023-09-14T14:48:11 IST" name="sl" finished-at="2023-09-14T14:48:12 IST" duration-ms="10" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [sreelanka] but found [srilanka]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [sreelanka] but found [srilanka]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at mavenpack.Assertclass.sl(Assertclass.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sl -->
      </class> <!-- mavenpack.Assertclass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
